version: "3"

volumes:
  staticfiles:
  postgres_data:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    volumes:
      - staticfiles:/app/staticfiles/
      - ./backend:/app/backend/
    command: sh -c "sh ./scripts/entrypoint.sh"
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    image: postgres:latest
    env_file:
      - backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - staticfiles:/app/staticfiles/