# Generated by Django 4.2 on 2023-06-12 11:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('complexity', models.PositiveSmallIntegerField(default=0)),
                ('is_many', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=255)),
                ('variants', models.JSONField()),
                ('answer', models.JSONField()),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.skills')),
            ],
        ),
    ]
