# Generated by Django 4.2 on 2023-06-02 10:09

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb017603-9abd-4a64-bc9b-f279373b5651'), primary_key=True, serialize=False),
        ),
    ]
