# Generated by Django 4.2 on 2023-06-12 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_description_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b8405be-8839-42fd-b045-61f9f8585900'), primary_key=True, serialize=False),
        ),
    ]
